export const EVENT_CONFIG = {
  eventName: "Joy of Giving",
  headline: "Share the Joy",
  subtitle: "Take a photo and share the joy of giving.",
  instagramHandles: [
    { handle: "@thegoodboxproject", url: "https://www.instagram.com/thegoodboxproject" },
    { handle: "@wittyinternationalschool", url: "https://www.instagram.com/wittyinternationalschool" },
  ],
  shareText: "I shared the joy this Joy of Giving Week. Join the movement and tag @thegoodboxproject and @wittyinternationalschool! ❤️",
  frames: [
    { id: "giving-books", src: "/frames/giving-books.png", thumbnailSrc: "/frames/lens-thumbnails/giving-books.webp", alt: "I am giving books." },
    { id: "helping-someone", src: "/frames/helping-someone.png", thumbnailSrc: "/frames/lens-thumbnails/helping-someone.webp", alt: "I will help someone who needs me." },
    { id: "saving-food", src: "/frames/saving-food.png", thumbnailSrc: "/frames/lens-thumbnails/saving-food.webp", alt: "I will not waste food." },
    { id: "donating-clothes", src: "/frames/donating-clothes.png", thumbnailSrc: "/frames/lens-thumbnails/donating-clothes.webp", alt: "I am donating clothes." },
    { id: "helping-learn", src: "/frames/helping-learn.png", thumbnailSrc: "/frames/lens-thumbnails/helping-learn.webp", alt: "I will help someone learn." },
    { id: "giving-hero", src: "/frames/giving-hero.png", thumbnailSrc: "/frames/lens-thumbnails/giving-hero.webp", alt: "Giving Hero" },
    { id: "donated", src: "/frames/donated.png", thumbnailSrc: "/frames/lens-thumbnails/donated.webp", alt: "I donated!" },
    { id: "kindness-star", src: "/frames/kindness-star.png", thumbnailSrc: "/frames/lens-thumbnails/kindness-star.webp", alt: "Kindness Star" },
    { id: "made-difference", src: "/frames/made-difference.png", thumbnailSrc: "/frames/lens-thumbnails/made-difference.webp", alt: "I made a difference!" },
    { id: "care-share", src: "/frames/care-share.png", thumbnailSrc: "/frames/lens-thumbnails/care-share.webp", alt: "I care and share." },
  ],
  outputWidth: 1080,
  outputHeight: 1350,
  cameraFacingMode: "user" as const,
  mirrorFrontCamera: true,
};
